### ISSUE TITLE
Database Error on buying a ticket

### ISSUE THREAD

**Issue by kuyashie** [ploidddddd/purplekeep#17]
1.) log in as a user
2.) choose a event
3.) click buy

![capture](https://user-images.githubusercontent.com/33778535/36323185-ff78d00c-138a-11e8-9c8c-5d048b176ac1.JPG)

**Comment by jenadrianne** [comment]
size : 2  
commit id : 
0503186

**Comment by jenadrianne** [comment]
VERIFIED
![image](https://user-images.githubusercontent.com/23441105/37135269-7ed9d8ea-22d7-11e8-90ed-00083da09ff3.png)
