### ISSUE TITLE
Advertisement placement in event details moves together with the page when scrolling down.

### ISSUE THREAD

**Issue by rpaulojade** [ploidddddd/purplekeep#177]
![ads](https://user-images.githubusercontent.com/28758500/36983889-87814c22-20ce-11e8-8030-659c5dc61f25.JPG)

![ads2](https://user-images.githubusercontent.com/28758500/36983890-87cf73c0-20ce-11e8-8505-286c08db4aad.JPG)

**Comment by leonillechristie** [comment]
ads removed
