### ISSUE TITLE
SPECIAL TASK : HEADER TAB ARE TO BE CHANGE TO ICONS

### ISSUE THREAD

**Issue by jenadrianne** [ploidddddd/purplekeep#211]

**Comment by seppjooo** [comment]
Commit IDs:

Initial Header Tabs Change: 
f111b81627c69d64ad692b79db69de637f819648

Create Event Page and Calendar Page Tabs Change: 
8b9e60b1e59d3b5dbd8720061f6c1866f2ff8e18

View Event Details Page Tabs Change: 
68cef7e369605765294b12a65b4ee3342d6b16fb

Create Event via Calendar Page Tabs Change:
f6eb0a33a23bacfb77f055793665b992b966ebf4
