### ISSUE TITLE
Load Card User: Show error message if inputted code is invalid or already used

### ISSUE THREAD

**Issue by kinrngl** [ploidddddd/purplekeep#22]

**Comment by seppjooo** [comment]
Commit ID: 48f96984cf3b83b9de52b1d58fe78e5d021bd534 
Size: 7

**Comment by jenadrianne** [comment]
VERIFIED
![image](https://user-images.githubusercontent.com/23441105/37134402-5cc266d6-22d3-11e8-92fa-77da5aedf2dd.png)
