### ISSUE TITLE
USER -> Calendar : When "Redeem Code" button is clicked, it must redirect to its current page

### ISSUE THREAD

**Issue by chinn015** [ploidddddd/purplekeep#220]
In Calendar Page, when you click the "Redeem Code" button, it must redirect to its current page not on Profile Page.

![issue016](https://user-images.githubusercontent.com/23441157/37030736-0976dc6c-2177-11e8-9459-5694a343d1a3.png)

**Comment by stspp091** [comment]
Done.
commit ID: 45e548b
