### ISSUE TITLE
ADMIN -> Quick Search : Remove quick search, since it doesn't work

### ISSUE THREAD

**Issue by Weeesh** [ploidddddd/purplekeep#229]
![image](https://user-images.githubusercontent.com/28923976/37038048-ac9f4d90-218e-11e8-93da-24e9ebd10b50.png)

**Comment by Weeesh** [comment]
82840d1eb3a7d967c6323aaaa98571130c2cdad3

**Comment by jenadrianne** [comment]
verified 
![image](https://user-images.githubusercontent.com/23441105/37352198-a968b696-2717-11e8-835f-5db47b765c48.png)
