### ISSUE TITLE
User Profile: Settings Page doesn't have its own container (Redundant to Edit Profile) 

### ISSUE THREAD

**Issue by kinrngl** [ploidddddd/purplekeep#24]
![settings](https://user-images.githubusercontent.com/32447414/36348921-714319ce-14b5-11e8-9f2c-885895634569.PNG)

**Comment by renmaxism** [comment]
issue fixed. Somebody else solved my assigned task. pffft...

**Comment by jenadrianne** [comment]
VERIFIED
![image](https://user-images.githubusercontent.com/23441105/37134449-84be4092-22d3-11e8-8986-f6b1aee63edc.png)
