### ISSUE TITLE
Event Details: Shows PHP error after clicking and redirecting to the event's details

### ISSUE THREAD

**Issue by seppjooo** [ploidddddd/purplekeep#25]
![image](https://user-images.githubusercontent.com/20873957/36350139-5b1dcb1c-1447-11e8-9a6e-4b1f1e6fab78.png)

**Comment by kristinepaola** [comment]
Fixed issue no. 25
Commit ID: fceeecd

**Comment by jenadrianne** [comment]
VERIFIED 
![image](https://user-images.githubusercontent.com/23441105/37134544-fd515d6e-22d3-11e8-828a-22b6356da05f.png)
