### ISSUE TITLE
ADMIN ->Event Management -> View attendees of Fight in Gotham doesn't show the attendees instead is put in the table outside

### ISSUE THREAD

**Issue by rpaulojade** [ploidddddd/purplekeep#252]
Fight in gotham
![event1](https://user-images.githubusercontent.com/28758500/37089232-d65f55ec-223a-11e8-8343-7932e567929c.JPG)
Another Event
![event2](https://user-images.githubusercontent.com/28758500/37089234-d6b7a42c-223a-11e8-998b-d8e400001e04.JPG)
Fight in gotham attendee crystal is in the table.
![event3](https://user-images.githubusercontent.com/28758500/37089235-d7138a4e-223a-11e8-8bd3-0d4f64a61c2e.JPG)

**Comment by Jeylin123** [comment]
1 pt 

commit ID = 2e393f4
