### ISSUE TITLE
Sign Up: Can register with birthdate inputted in the future 

### ISSUE THREAD

**Issue by renmaxism** [ploidddddd/purplekeep#26]
![image](https://user-images.githubusercontent.com/33869151/36350196-f75a6c64-1448-11e8-8d44-deea13fe44b5.png)

**Comment by chinn015** [comment]
fixed by: Christine Diane Malazarte
size : 3
commit id: 88fb417

**Comment by jenadrianne** [comment]
VERIFIED
![image](https://user-images.githubusercontent.com/23441105/37134943-cb4a6020-22d5-11e8-9605-70464876e4ac.png)
