### ISSUE TITLE
ADMIN : REMOVE PROFILE IN DROPDOWN 

### ISSUE THREAD

**Issue by jenadrianne** [ploidddddd/purplekeep#279]
![image](https://user-images.githubusercontent.com/23441105/37136356-370ff882-22dc-11e8-812c-2bed9e61732c.png)

**Comment by famasboy888** [comment]
Removed this na: https://github.com/ploidddddd/purplekeep/commit/c553cb0f7a6b4d6aaa2b1da86e78479b6d5715f8
