### ISSUE TITLE
Edit Profile: Error Code 404 shows up after clicking Edit Profile button

### ISSUE THREAD

**Issue by renmaxism** [ploidddddd/purplekeep#28]
![image](https://user-images.githubusercontent.com/33869151/36350240-232f134e-14d0-11e8-8f47-0dbf69ca26f7.png)

**Comment by jenadrianne** [comment]
VERIFIED

ADMIN 
![image](https://user-images.githubusercontent.com/23441105/37135004-2c9d70a6-22d6-11e8-9e95-af7024498712.png)

USER 
![image](https://user-images.githubusercontent.com/23441105/37135007-3219f572-22d6-11e8-9af3-dfa3c562cd87.png)
