### ISSUE TITLE
Create Event: Can create an Event with Start Date inputted in the past or End Date inputted in the past

### ISSUE THREAD

**Issue by renmaxism** [ploidddddd/purplekeep#29]
Start Date inputted in the past:
![image](https://user-images.githubusercontent.com/33869151/36350474-6a64b36a-14d3-11e8-88ee-b7bf825da2db.png)

End Date inputted in the past:
![image](https://user-images.githubusercontent.com/33869151/36350528-571f933c-14d4-11e8-825d-c44781421847.png)

**Comment by jenadrianne** [comment]
VERIFIED 
![image](https://user-images.githubusercontent.com/23441105/37135094-9cac3ecc-22d6-11e8-8929-991bb67ee308.png)
