### ISSUE TITLE
EVENTS button in front page doesn't do anything.

### ISSUE THREAD

**Issue by domjoeymoncada** [ploidddddd/purplekeep#31]
![issues](https://user-images.githubusercontent.com/28528979/36351126-d92c42ac-14df-11e8-9e0f-b591d2267a92.png)

**Comment by seppjooo** [comment]
Commit ID: c4db488a9bc3acf2683b2208777dd139f355f1ed
Size: 4

**Comment by jenadrianne** [comment]
VERIFIED
