### ISSUE TITLE
Password in password text field in EDIT PROFILE is the hashed value

### ISSUE THREAD

**Issue by domjoeymoncada** [ploidddddd/purplekeep#32]
![hashed](https://user-images.githubusercontent.com/28528979/36351184-f8559394-14e0-11e8-8136-dff988f492a4.png)
maybe change to NEW PASSWORD? idk

**Comment by Ted125** [comment]
i opened that issue on the old repo. Delete this.

https://github.com/ejmstark/event_system/issues/409
