### ISSUE TITLE
SELECT ALL in VIEW CART tab gets overlapped by footer

### ISSUE THREAD

**Issue by domjoeymoncada** [ploidddddd/purplekeep#34]
![overlapped](https://user-images.githubusercontent.com/28528979/36351537-9c9b41b0-14e6-11e8-936a-3d12797ae4e5.png)

**Comment by renmaxism** [comment]
issue solved by somebody else againn.. tsssssssssssss :-1:

**Comment by jenadrianne** [comment]
VERIFIED 
![image](https://user-images.githubusercontent.com/23441105/37135489-7da1e91c-22d8-11e8-9dce-ece6016f55aa.png)
