### ISSUE TITLE
User: View Cart -> Checkout button doesn't work

### ISSUE THREAD

**Issue by erynvinnice** [ploidddddd/purplekeep#36]
![image](https://user-images.githubusercontent.com/33870088/36351561-eb5e9e82-14e6-11e8-825e-fb074f1623ef.png)

**Comment by algreg1998** [comment]
Commit ids:

d8d0558e019563cac7b293887e0d981562ec539f
bb294590beffeafdf9711d21010e6b2a2f79543c
abe1b8c0a8264bf9773da173c8665675355e343b
90d7fa3a5ce2613eefd70a15e67bad69bdf17ec0
3fb0142f0a0fd46758ef9967b589008a4ce2a0d6

**Comment by jenadrianne** [comment]
![image](https://user-images.githubusercontent.com/23441105/37136730-d13caa08-22dd-11e8-8c7d-af9730e68e3c.png)
![image](https://user-images.githubusercontent.com/23441105/37136732-d2c664ea-22dd-11e8-8acb-a1b8cbc65ae4.png)

VERIFIED
