### ISSUE TITLE
Create Event: Creating an event is successful but shows "Error Code: 404" Page before redirecting to Home Page. Inform user when Create Event is successful

### ISSUE THREAD

**Issue by seppjooo** [ploidddddd/purplekeep#38]
![image](https://user-images.githubusercontent.com/20873957/36352035-58435064-14ed-11e8-9769-f090a068a790.png)

**Comment by duenaser** [comment]
ok ra na lagi ni?

**Comment by renmaxism** [comment]
Size: 6

**Comment by renmaxism** [comment]
commit id : ccf225b59d83f75cd5f0183d7e9deaa3a66fedac

**Comment by jenadrianne** [comment]
VERIFIED 
![image](https://user-images.githubusercontent.com/23441105/37135587-da86af0a-22d8-11e8-8335-cb9561187543.png)
