### ISSUE TITLE
Reopened: Announcements tab is Missing on View Cart page from sprint 6 issue #389 not fixed. #424

### ISSUE THREAD

**Issue by Dioven15** [ploidddddd/purplekeep#4]
Commit ID: 89ff82d
Size: 4

**Comment by Dioven15** [comment]
https://github.com/ejmstark/event_system/issues/424

**Comment by jenadrianne** [comment]
![image](https://user-images.githubusercontent.com/23441105/37133843-9341d8a2-22d0-11e8-8edf-6c1dfd67fb2a.png)


verified
