### ISSUE TITLE
Admin Tabs Duplicate Icon: Use appropriate icons for Announcements and Update Account tabs 

### ISSUE THREAD

**Issue by seppjooo** [ploidddddd/purplekeep#57]
![asd](https://user-images.githubusercontent.com/20873957/36478247-0eedf64a-173f-11e8-8449-1bc70590d64c.png)

**Comment by renmaxism** [comment]
size: 3

**Comment by renmaxism** [comment]
commit id : 3a14de39fdb65e54b6a6285f3c80c55760a5ee99

**Comment by jenadrianne** [comment]
verified
![image](https://user-images.githubusercontent.com/23441105/37136514-ed62a828-22dc-11e8-84c5-7496dedfcd40.png)
