### ISSUE TITLE
Edit Event Page: Missing "Interested Events" Tab on header

### ISSUE THREAD

**Issue by renmaxism** [ploidddddd/purplekeep#60]
![image](https://user-images.githubusercontent.com/33869151/36479243-eeb6cbd2-1742-11e8-8f24-6476ce1e593b.png)

**Comment by seppjooo** [comment]
Commit ID: abace4ab13f0e6eb4262cb9a7d6a6526f262bb07
Size: 2

**Comment by jenadrianne** [comment]
![image](https://user-images.githubusercontent.com/23441105/37136596-37c8aad4-22dd-11e8-8efb-2cc34d8d05fe.png)
