### ISSUE TITLE
Sign Up/Edit Profile: Gender value after Signing Up does not match when viewing the values in the Edit Profile Page

### ISSUE THREAD

**Issue by renmaxism** [ploidddddd/purplekeep#61]
Test case:
I signed up an account with a Female gender.
When trying to Edit Profile, the gender value showed Male.

**Comment by fchryssreitimothy** [comment]
Size: 3

**Comment by jenadrianne** [comment]
verified
![image](https://user-images.githubusercontent.com/23441105/37351796-d2f013e8-2716-11e8-8c39-b609c10db781.png)
