### ISSUE TITLE
User: Calendar -> Interested Events tab is missing

### ISSUE THREAD

**Issue by erynvinnice** [ploidddddd/purplekeep#64]
![image](https://user-images.githubusercontent.com/33870088/36480729-59cbd8c2-1748-11e8-87bc-0dac00964cb8.png)

**Comment by chinn015** [comment]
Fixed by : Joanne Malaluan
size: 2
commit id: 8d2c6fc

**Comment by jenadrianne** [comment]
VERIFIED 
![image](https://user-images.githubusercontent.com/23441105/37136407-82d57c6a-22dc-11e8-92de-13231902e31c.png)
