### ISSUE TITLE
Admin: Transfer "Update Account" from Sidebar to the Dropdown Settings

### ISSUE THREAD

**Issue by seppjooo** [ploidddddd/purplekeep#67]
![image](https://user-images.githubusercontent.com/20873957/36484819-69c90986-1755-11e8-8d60-b477f0fcd779.png)

**Comment by renmaxism** [comment]
Size: 4

**Comment by renmaxism** [comment]
commit id : 52b5271256d0e0c3a1bb7a9fc059254c3603d831

**Comment by jenadrianne** [comment]
verified : 
![image](https://user-images.githubusercontent.com/23441105/37136334-1d1d5488-22dc-11e8-96e6-864b52fc3a77.png)
