### ISSUE TITLE
USER: Create Event --> Event Picture file input must only accept recommended image file type

### ISSUE THREAD

**Issue by jcdans** [ploidddddd/purplekeep#8]
Anticipation right after the create event module will be fixed. Uploaded picture for event picture must prohibit any other file types other than image file types(jpg, gif, png, etc).
![image](https://user-images.githubusercontent.com/28702627/36317683-bd92274a-1378-11e8-9749-b3b53df86ee0.png)

**Comment by angeloglim** [comment]
Issue is already fixed. Not valid extension will be given a default image.

**Comment by jenadrianne** [comment]
verification : upload images are currently disabled in live
