### ISSUE TITLE
USER: Signup -> Login Button in viewRegistrationConfirmation view does not work

### ISSUE THREAD

**Issue by jcdans** [ploidddddd/purplekeep#83]
![tedissue-00](https://user-images.githubusercontent.com/28702627/36689441-5ac86fc6-1b6a-11e8-9e38-e8a1da6300b7.png)

Issue Created on Old Repo

**Comment by jcdans** [comment]
Issue Resolved.

Commit ID : a60172c

**Comment by jenadrianne** [comment]
![image](https://user-images.githubusercontent.com/23441105/37136144-4f25317c-22db-11e8-8f7c-48117dfed9bb.png)

VERIFIED
