### ISSUE TITLE
USER->VIEW CART: Php error when "View Cart" is clicked

### ISSUE THREAD

**Issue by duenaser** [ploidddddd/purplekeep#87]

**Comment by algreg1998** [comment]
Akoy naka solve ani.. sa pc sa school lang akong na gamit wala nako na config ang username and password
b012fe84d3415b0336e5dbccc6322dc5102dfa88

**Comment by algreg1998** [comment]
kani ray naka solve 

![image](https://user-images.githubusercontent.com/20896859/36729243-81cdb1d2-1bfe-11e8-9aa9-3ec47d3f5752.png)
