### ISSUE TITLE
USER: Create Event --> Supporting Ted Ochoa's Issue (No available municipalities in every region). 

### ISSUE THREAD

**Issue by jcdans** [ploidddddd/purplekeep#9]
An assessment to Ted Ochoa's issue, since the "City/Municipal" input field, registering the event would result in to a back end error. I removed the municipal input field to simulate the creation of an event.
![image](https://user-images.githubusercontent.com/28702627/36318043-aea47c5a-1379-11e8-85f4-f42fc00e61f2.png)

**Comment by algreg1998** [comment]
Commit Id:
a0a7857107c053cd578168d73a675e9ca8baa01a

**Comment by jenadrianne** [comment]
![image](https://user-images.githubusercontent.com/23441105/37133961-189f3e18-22d1-11e8-8a59-0c97fbd4386f.png)


VERIFIED
